a.out: main.cpp MULRLexer.cpp TokenBuilder.cpp TokenChecker.cpp TokenFeed.cpp TokenGenerator.cpp ListGen.cpp
	clang++ -o a.out main.cpp MULRLexer.cpp TokenBuilder.cpp TokenChecker.cpp TokenFeed.cpp TokenGenerator.cpp ListGen.cpp
