a.out: main.cpp lexer/MULRLexer.cpp lexer/TokenBuilder.cpp lexer/TokenChecker.cpp lexer/TokenFeed.cpp lexer/TokenGenerator.cpp generator/ListGen.cpp
	clang++ -o ../executable/a.out main.cpp lexer/MULRLexer.cpp lexer/TokenBuilder.cpp lexer/TokenChecker.cpp lexer/TokenFeed.cpp lexer/TokenGenerator.cpp generator/ListGen.cpp -I lexer -I generator
